### ISSUE TITLE
Remove templating for docker files

### ISSUE THREAD

**Issue by mcquinne** [cedardevs/metadata-catalog#113]
### Motivation

The variables that are substituted into the various templates that build a Dockerfile and docker-compose.yml for each subproject are almost entirely constant. The setup could be simplified significantly by just using plain docker files with docker's own mechanisms for the few pieces that need to dynamic.

### Proposal

Use [Dockerfile ARG directive](https://docs.docker.com/engine/reference/builder/#arg) + [docker-compose build args](https://docs.docker.com/compose/compose-file/#args) + [docker-compose variable substitution](https://docs.docker.com/compose/compose-file/#variable-substitution) to handle the dynamic values.

#### index/docker-compose-dependencies.yml

To spin up the dependencies need to run index component tests

```yml
version: '2'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    environment:
     - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      index:
        aliases: []
  rabbit:
    image: rabbitmq:management
    ports:
     - "5672:5672"
     - "15672:15672"
    networks:
      index:
        aliases: []
networks:
  index: {}
```
#### index/Dockerfile

To build the index image

```Dockerfile
FROM openjdk:8
ARG NAME
ARG VERSION
WORKDIR /usr/src/app
COPY build/libs/${NAME}-${VERSION}.jar .
RUN ln -s ./${NAME}-${VERSION}.jar app.jar
LABEL version=${VERSION}
...
EXPOSE 8080
CMD java -jar /usr/src/app/app.jar
```

#### api/docker-compose-dependencies.yml

To set up the dependencies to run api component tests, including the index image

```yml
version: '2'
services:
  index:
    build:
      context: ./index/
      args:
        - NAME: index
        - VERSION: ${VERSION}
    image: org.cedar/metadata-catalog-index:${VERSION}
    ports:
     - "8082:8080"
    environment:
     - elasticsearch_host=es
     - rabbitmq_connectionfactory_host=rabbit
    networks:
      api:
        aliases: []
...
```
